services:
  feed_collector:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        YTDLP_DATE: ${YTDLP_DATE:-}
    container_name: feed_collector
    volumes:
      - ../feeds_data:/app/feeds_data
      - ../assets:/app/assets
      - ../feeds_config.yaml:/app/feeds_config.yaml
      - ../.env:/app/.env
      - ../data:/app/data
    environment:
      - TZ=America/Bogota
    command: sh -c "python src/feed_fetcher.py ${FORCE_ARG}"
    networks:
      - feeds_network
    restart: "no"

networks:
  feeds_network:
    driver: bridge
